### ISSUE TITLE
Необходимо обновление

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_CustomTags#1]
Здравствуйте, добавьте пожалуйста новые тэги в **ElvUI_CustomTags**, так как на сайте [www.tukui.org ](https://www.tukui.org/forum/viewtopic.php?t=22) (прямая ссылка на топик **Unitframe Custom Tags**) добавлено очень много новых тегов, что существенно расширит функционал ElvUI-WotLK. Спасибо

**Comment by Bunny67** [comment]
Добавил отсутвующие
